DROP TABLE IF EXISTS `SEQUENCE_CONFIG`;

CREATE TABLE `SEQUENCE_CONFIG` (
  `SEQ_NAME` varchar(255) NOT NULL COMMENT '序列名称',
  `MIN_VAL` decimal(35,0) NOT NULL COMMENT '最小值',
  `MAX_VAL` decimal(35,0) NOT NULL COMMENT '最大值',
  `CUR_VAL` decimal(35,0) NOT NULL COMMENT '当前使用值',
  `STEP_VAL` int(10) NOT NULL DEFAULT '1' COMMENT '递增值',
  `CYCLE` char(1) NOT NULL DEFAULT 'Y' COMMENT '是否循环,默认为Y表示循环',
  `UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`SEQ_NAME`)
) ENGINE=InnoDB COMMENT='序列号';